### ISSUE TITLE
Icons in Anybox don't match Alfred if icon changed

### ISSUE THREAD

**Issue by epetrack1** [anyboxhq/anybox-alfred-workflow#8]
Minor issue, but would be great if this could be fixed.... I use the app Hook (now called Hookmark) to "enhance" linking across apps. If I add a link to Anybox that was copied using Hookmark, the icon in Anybox is the Hookmark Icon. My workflow is to then change that icon (easy to do.... CMD-D) to the actual app (in attached example, Apple Notes). While this then shows the Notes icon in Anybox, in Alfred, it still shows the Hookmark icon (see attachment). I appreciate this may be beyond what can be done here, but would be great to quickly visually see the correct icon using Alfred- thanks!
![Anybox- Icon Issue](https://github.com/user-attachments/assets/54f2ed48-5d93-408d-9aef-2c0e06e75fdf)

**Comment by francisfeng** [comment]
What the Anybox workflow is doing here is that it gets the links icons from Anybox app and saves the result to disk. And then it shows the icons from disk and never ask for it again.

Essentially the workflow caches the links icons. You can go to the Alfred Workflows and select “Open in Folder”, and then delete the “Link Icons” folder. So that the workflow can ask for the icons again.

It’s not prefect. But I don’t think there’s an easy way to fix this.

![Alfred setting](https://github.com/user-attachments/assets/a3a3e035-181c-44ed-932d-8d0b0766dafe)
